"""System diagnostics: app-integrity report.

GET returns the cached report from the last startup run (cheap, no re-run);
POST re-runs the battery live for the Diagnostics panel's "Re-check" button.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.startup_checks import check_app_integrity, get_app_integrity

router = APIRouter(prefix="/api/v1/system", tags=["system"])


@router.get("/integrity")
async def get_integrity() -> dict[str, Any]:
    """Cached app-integrity report from the last startup run."""
    return get_app_integrity()


@router.post("/integrity")
async def refresh_integrity() -> dict[str, Any]:
    """Re-run the integrity battery live and return the fresh report."""
    return await check_app_integrity()


@router.post("/integrity/rebuild-search-index")
async def rebuild_search_index() -> dict[str, Any]:
    """Repopulate the FTS search index, then return the refreshed integrity report."""
    from app.core.database import rebuild_search_index as do_rebuild

    await do_rebuild()
    return await check_app_integrity()


@router.get("/egress-report")
async def egress_report(db: AsyncSession = Depends(get_db)) -> dict[str, Any]:
    """Enumerate every surface that can send data off the device.

    Privacy is LifeLogr's headline promise, so data egress must be auditable.
    Each surface reports whether it is currently active and whether using it
    sends journal content off the machine. The Privacy settings tab renders this
    verbatim — nothing leaves the device unless explicitly turned on here.
    """
    from app.models.backup import BackupConfig, BackupSchedule
    from app.services.ai_provider_service import get_active_provider

    # Cloud AI: the active provider, unless it is the local Ollama preset.
    ai_provider = await get_active_provider()
    ai_cloud = ai_provider is not None and ai_provider.preset != "ollama"
    cloud_ai = {
        "leaves_device": ai_cloud,
        "active": ai_provider is not None,
        "provider": ai_provider.name if ai_provider else "local Ollama",
        "preset": ai_provider.preset if ai_provider else "ollama",
        "note": (
            "Running any AI tool on an entry or note sends its text to this "
            "provider — it leaves your device."
            if ai_cloud
            else "AI tools run on your machine via local Ollama."
        ),
    }

    # Cloud backup: any configured provider. Whether it actually runs is governed
    # by the single active BackupSchedule (id=1).
    configs = (await db.execute(select(BackupConfig))).scalars().all()
    configured = [
        {"provider": c.provider, "label": c.label or c.provider, "leaves_device": True}
        for c in configs
    ]
    sched = (
        await db.execute(select(BackupSchedule).where(BackupSchedule.id == 1))
    ).scalar_one_or_none()
    scheduled = sched is not None and sched.config_id is not None
    cloud_backup = {
        "configured": configured,
        "scheduled": scheduled,
        "note": (
            "A scheduled cloud backup uploads an encrypted archive of your journal to the provider."
            if scheduled
            else "No cloud backup is scheduled. (Configured providers only run when you back up.)"
        ),
    }

    return {
        "cloud_ai": cloud_ai,
        "cloud_backup": cloud_backup,
        "web_clip": {
            "leaves_device": False,
            "note": "When you clip a web address, the backend fetches that page to "
            "extract its text. The URL leaves your machine; your journal data does not.",
        },
        "ocr": {
            "leaves_device": False,
            "engine": "tesseract",
            "note": "Image text recognition runs locally with Tesseract.",
        },
        # Embeddings route through the active AI provider too, so they leave the
        # device when cloud AI is on — not just the chat tools.
        "embeddings": {
            "leaves_device": ai_cloud,
            "note": (
                "Vector embeddings are generated by the active AI provider, which "
                "is a cloud provider here."
                if ai_cloud
                else "Vector embeddings are generated locally by Ollama."
            ),
        },
    }
